/**
 * Core types for Delve taxonomy generation.
 */

/**
 * Represents a document in the taxonomy generation process.
 */
export interface Doc {
  /** Unique document identifier */
  id: string;
  /** Document text content */
  content: string;
  /** LLM-generated summary (populated during processing) */
  summary?: string;
  /** Explanation for the assigned category */
  explanation?: string;
  /** Assigned category name */
  category?: string;
}

/**
 * A taxonomy category generated by Delve.
 */
export interface TaxonomyCategory {
  /** Unique category identifier */
  id: string;
  /** Category name (concise label) */
  name: string;
  /** Category description (explains what belongs in this category) */
  description: string;
}

/**
 * Metrics from classifier training (when sample_size < total docs).
 */
export interface ClassifierMetrics {
  trainAccuracy: number;
  testAccuracy: number;
  trainF1: number;
  testF1: number;
}

/**
 * Metadata about a taxonomy generation run.
 */
export interface DelveMetadata {
  /** Total number of documents processed */
  numDocuments: number;
  /** Number of categories in the taxonomy */
  numCategories: number;
  /** Configured sample size */
  sampleSize: number;
  /** Configured batch size */
  batchSize: number;
  /** Main model used */
  model: string;
  /** Fast model used for summarization */
  fastLlm: string;
  /** Total processing time in seconds */
  runDurationSeconds: number;
  /** Document count per category */
  categoryCounts: Record<string, number>;
  /** Documents labeled by LLM */
  llmLabeledCount: number;
  /** Documents labeled by classifier */
  classifierLabeledCount: number;
  /** Documents that couldn't be categorized */
  skippedDocumentCount: number;
  /** Classifier metrics (if classifier was used) */
  classifierMetrics?: ClassifierMetrics;
  /** Processing warnings */
  warnings: string[];
  /** Status log */
  statusLog: string[];
}

/**
 * Complete result from taxonomy generation.
 */
export interface DelveResult {
  /** Generated taxonomy categories */
  taxonomy: TaxonomyCategory[];
  /** All documents with assigned categories */
  labeledDocuments: Doc[];
  /** Run metadata and statistics */
  metadata: DelveMetadata;
}

/**
 * Configuration options for Delve.
 */
export interface DelveConfig {
  /**
   * Main LLM model for taxonomy generation and reasoning.
   * @default "claude-sonnet-4-5-20250929"
   */
  model?: string;

  /**
   * Faster model for document summarization.
   * @default "claude-haiku-4-5-20251001"
   */
  fastLlm?: string;

  /**
   * Number of documents to sample for LLM labeling.
   * Set to 0 to process all documents with LLM.
   * @default 100
   */
  sampleSize?: number;

  /**
   * Number of documents per minibatch during iterative clustering.
   * @default 200
   */
  batchSize?: number;

  /**
   * Maximum number of categories to generate.
   * @default 5
   */
  maxNumClusters?: number;

  /**
   * Custom description of the taxonomy use case.
   * Helps guide the model to generate relevant categories.
   */
  useCase?: string;

  /**
   * OpenAI embedding model for classifier training.
   * @default "text-embedding-3-large"
   */
  embeddingModel?: string;

  /**
   * Minimum confidence for classifier predictions.
   * Documents below threshold fall back to LLM labeling.
   * @default 0.0
   */
  classifierConfidenceThreshold?: number;

  /**
   * Anthropic API key. If not provided, uses ANTHROPIC_API_KEY env var.
   */
  anthropicApiKey?: string;

  /**
   * OpenAI API key (for embeddings). If not provided, uses OPENAI_API_KEY env var.
   */
  openaiApiKey?: string;
}

/**
 * Predefined category for direct labeling (skip taxonomy discovery).
 */
export interface PredefinedCategory {
  id: string;
  name: string;
  description: string;
}

/**
 * Input options for running taxonomy generation.
 */
export interface RunOptions {
  /**
   * Custom use case description (overrides config).
   */
  useCase?: string;

  /**
   * Use predefined categories instead of generating taxonomy.
   */
  predefinedTaxonomy?: PredefinedCategory[];
}

/**
 * Internal state for the LangGraph workflow.
 */
export interface GraphState {
  /** All documents (before sampling) */
  allDocuments: Doc[];
  /** Sampled documents for processing */
  documents: Doc[];
  /** Minibatch indices */
  minibatches: number[][];
  /** Taxonomy iterations (list of cluster lists) */
  clusters: TaxonomyCategory[][];
  /** Use case description */
  useCase: string;
  /** Status messages */
  status: string[];
  /** Classifier metrics */
  classifierMetrics?: ClassifierMetrics;
  /** LLM labeled count */
  llmLabeledCount: number;
  /** Classifier labeled count */
  classifierLabeledCount: number;
  /** Skipped document count */
  skippedDocumentCount: number;
  /** Warnings */
  warnings: string[];
}
